version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - mynetwork
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
networks:
  mynetwork:
